from infrastructure.create_security_group import create_security_group
from infrastructure.create_instances import create_orchestrator_and_workers
from tools.instance_discovery import save_instance_ips
from benchmark.load_test import run_benchmark
from infrastructure.destroy_infrastructure import destroy_all